### ISSUE TITLE
Advanced footer section

### ISSUE THREAD

**Issue by Aditi323** [fluttergems/awesome-open-source-flutter-apps#1]
![Screenshot (352)](https://github.com/fluttergems/awesome-open-source-flutter-apps/assets/114893448/7287cd77-6728-40b0-951b-66c004352a4d)
I want to enhance the footer section and also add icons and redirecting links 
Please assign this to me under GSSOC'24

**Comment by Gokilp** [comment]
please assign to me #gssoc24

**Comment by ashitaprasad** [comment]
Please read the contributing guide.
