### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by sanjay-kv** [fluttergems/awesome-open-source-flutter-apps#11]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow [these](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-using-a-template) instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by hariram62** [comment]
@ashitaprasad I would like to contribute to this issue. Can u pls assign me ?
