### ISSUE TITLE
to add open source flutter app

### ISSUE THREAD

**Issue by a-m-a-nkumar** [fluttergems/awesome-open-source-flutter-apps#122]
Voting Dapp

https://github.com/a-m-a-nkumar/voting_dapp

Voting Dapp is a decentralised voting platform based on blockchain.

Category: Blockchain , Flutter , Solidity Contracts

**Comment by a-m-a-nkumar** [comment]
I am a GSSOC Contributor . Please assign me this issue.

**Comment by ashitaprasad** [comment]
The project's readme is incomplete.
