### ISSUE TITLE
to add open source flutter app "Ebook-App"

### ISSUE THREAD

**Issue by Asymtode712** [fluttergems/awesome-open-source-flutter-apps#133]
### Ebook-App

(https://github.com/md-durjoy/Ebook-App)

Flutter eBook reader app! Browse genres, bookmark favorites, and customize your reading experience. Find books fast with their search feature. 

**Category: Books**

**Comment by Asymtode712** [comment]
@ashitaprasad please assign me this issue

**Comment by ashitaprasad** [comment]
The github repo does not exist.
