### ISSUE TITLE
Add FOSS app "Track My Indoor Workout"

### ISSUE THREAD

**Issue by MrCsabaToth** [fluttergems/awesome-open-source-flutter-apps#141]
### Track My Indoor Workout

(https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout)

Track My Indoor Workout is an application to record stationary workouts of smart fitness machines via BLE protocol. Workouts can have virtual GPS routes and can be uploaded to fitness portals or downloaded.

Category: Health & Fitness

**Comment by MrCsabaToth** [comment]
Note that I was browsing https://fluttergems.dev/packages/flutter_blue_plus/ and as a contributor to that project I thought my project qualifies to be listed. I'm not sure how the categories here in the README will make the project in the end listed in https://fluttergems.dev/packages/flutter_blue_plus/

My app could be also considered in the `Network, Bluetooth & Sharing`, and slightly in the `Utilities`, however it's mostly `Health & Fitness` in nature with a strong emphasis on Bluetooth Low Energy communication

**Comment by ashitaprasad** [comment]
Thanks for adding the open source app. 
Will close this issue once it is added to the list.
