### ISSUE TITLE
to add open source flutter app

### ISSUE THREAD

**Issue by Vipullakum007** [fluttergems/awesome-open-source-flutter-apps#175]
Momento

(https://github.com/HemantPra389/Flutter-Open-Source-Apps/tree/main/Flutter%20Open%20Source%20Apps/Intermediate/Momento)

A Feature Rich Google Keep Like Notes App Written In Flutter With Beautiful UI.

Category : Store

**Comment by ashitaprasad** [comment]
The app should have its own repo.
