### ISSUE TITLE
Track My Indoor Workout doesn't show up on the https://fluttergems.dev/packages/flutter_blue_plus/ page as FOSS project

### ISSUE THREAD

**Issue by MrCsabaToth** [fluttergems/awesome-open-source-flutter-apps#193]
The app was added #141 and PR was merged, however when I visit https://fluttergems.dev/packages/flutter_blue_plus/ I still don't see it listed.

**Comment by ashitaprasad** [comment]
The migration to this repo is still in progress.
Will close the issue once it is complete.

**Comment by ashitaprasad** [comment]
The migration is complete. Thanks.
