### ISSUE TITLE
Misalignment of Cards

### ISSUE THREAD

**Issue by lakshyajn** [fluttergems/awesome-open-source-flutter-apps#2]
![Screenshot 2024-05-09 170736](https://github.com/fluttergems/awesome-open-source-flutter-apps/assets/162354839/132fd234-0c92-454a-af7e-76c8655be6e1)

Hey, I found this issue about improper alignment of these cards, I can do this :)

Please Assign it to me...
It would be nice to work upon this issue

**Comment by Gokilp** [comment]
please assign to me #gssoc24

**Comment by ashitaprasad** [comment]
Please read the contributing guide.
