### ISSUE TITLE
Adding Open-Source Flutter Apps to Repository

### ISSUE THREAD

**Issue by Unnimaya6122004** [fluttergems/awesome-open-source-flutter-apps#20]
adding several open-source Flutter apps to our current repository to foster collaboration and provide valuable resources to the community. Below is a list of the apps I am  suggesting to include:

### **Reflectly**

GitHub Repository: [https://github.com/topics/reflectly]
Description: Reflectly is a journaling app designed to help users foster a positive mindset and improve their mental well-being through daily reflections.

### **Inkino**

GitHub Repository: [https://github.com/dreambuilder00/inKino-Flutter]
Description: Inkino is a movie discovery app that allows users to explore movies playing in theaters, check showtimes, and read reviews.

### **Watermaniac**

GitHub Repository: [https://github.com/artur-ios-dev/watermaniac]
Description: Watermaniac is a hydration tracking app that helps users stay hydrated throughout the day by providing reminders and tracking water intake.

### **Natrium**

GitHub Repository: [https://github.com/appditto/natrium_wallet_flutter]
Description: Natrium is a Nano cryptocurrency wallet app, providing users with a secure and intuitive way to manage their Nano funds.

**Comment by Unnimaya6122004** [comment]
can u pls assign me this issue...its my first time contributing to an open source..so i want to learn more about it

**Comment by Unnimaya6122004** [comment]
thnku...can u also tell me what the next step to do...is it the pull request

**Comment by ashitaprasad** [comment]
Yes, send across a PR.

**Comment by Unnimaya6122004** [comment]
i have send a PR...can u check it if everything is okay or not..

**Comment by ashitaprasad** [comment]
Replied on the PR. Make sure you make the requisite changes.
