### ISSUE TITLE
Want to add Dino Run game

### ISSUE THREAD

**Issue by nishant0708** [fluttergems/awesome-open-source-flutter-apps#229]
want to add Dino Run game
![Screenshot (244)](https://github.com/fluttergems/awesome-open-source-flutter-apps/assets/101548649/71f113f3-846a-4c49-8c6c-a377616509e3)

**Comment by ashitaprasad** [comment]
Add the github repo link as well.

**Comment by nishant0708** [comment]
Yes I will

**Comment by ashitaprasad** [comment]
Add the github repo link, here in the issue as well.

**Comment by nishant0708** [comment]
https://github.com/ufrshubham/dino_run
