### ISSUE TITLE
Want to add Club Penguin Game

### ISSUE THREAD

**Issue by nishant0708** [fluttergems/awesome-open-source-flutter-apps#230]
Want to add Club Penguin Game
![Screenshot 2024-06-20 144257](https://github.com/fluttergems/awesome-open-source-flutter-apps/assets/101548649/97f27439-13d9-4a12-b3db-3307d8f94950)

**Comment by ashitaprasad** [comment]
Add the github repo link.

**Comment by nishant0708** [comment]
Yaa I will

**Comment by nishant0708** [comment]
https://github.com/Shadow60539/club_penguin_game
