### ISSUE TITLE
Want to add bananaMon Game

### ISSUE THREAD

**Issue by nishant0708** [fluttergems/awesome-open-source-flutter-apps#231]
want to add bananaMon game , 
![Screenshot 2024-06-20 144822](https://github.com/fluttergems/awesome-open-source-flutter-apps/assets/101548649/9dde47f4-73d7-42d2-90ef-ae175c47a736)
a new bombman-like game in flutter

**Comment by ashitaprasad** [comment]
Also add the github repo link.

**Comment by nishant0708** [comment]
I will

**Comment by ashitaprasad** [comment]
Add the github repo link here, in the issue.

**Comment by nishant0708** [comment]
https://github.com/hotstu/flutter_BananaMon?tab=readme-ov-file
