### ISSUE TITLE
Addition of Flutter Photo Manager 

### ISSUE THREAD

**Issue by StutiRajput07** [fluttergems/awesome-open-source-flutter-apps#24]
**Addition of Flutter Photo Manager under Photos and Videos section**

Flutter plugin is a powerful tool for developers looking to handle media files across different operating systems without dealing with the specifics of each platform’s file management system. The plugin abstracts these details, providing a unified API to access and manage images, videos, and audio files, while leaving the UI design and integration entirely up to the developer.

**Comment by ashitaprasad** [comment]
Only open source flutter apps have to be added.
