### ISSUE TITLE
Addition of Explr Project under books section

### ISSUE THREAD

**Issue by StutiRajput07** [fluttergems/awesome-open-source-flutter-apps#26]
Explr aims at providing a platform for users where they can know what their friends are reading and exchange books with them, along with knowing which book is the talk of the town. Addition of this project will be beneficial.

**Comment by ashitaprasad** [comment]
Closing this issue as PR is merged. From the next time, make sure that you link your issue to the PR raised.

**Comment by StutiRajput07** [comment]
Ok I will .
Thanks
