### ISSUE TITLE
Add a Rental Store Application 

### ISSUE THREAD

**Issue by JyotikaJayani-08** [fluttergems/awesome-open-source-flutter-apps#276]
I want to add a app where people can rent costly clothes and accessories for some days by paying a charge per day.
@ashitaprasad please can you assign me this issue.
It will look like this.
![rental_app](https://github.com/fluttergems/awesome-open-source-flutter-apps/assets/158709375/adfc2326-2a73-455c-83a1-b8285ebd501e)

**Comment by ashitaprasad** [comment]
Add the github repo link.
