### ISSUE TITLE
Add table of contents

### ISSUE THREAD

**Issue by Vaibhav2154** [fluttergems/awesome-open-source-flutter-apps#287]
As this repository contains many sections and the user might find it difficult to navigate through the repository.
I want to add a table of contents of the various sections such that it would redirect to that section.
I'm a contributor at Gssoc Please assign me this issue with suitable labels

**Comment by Vaibhav2154** [comment]
@ashitaprasad Its not implemented 
![Screenshot_20240629_170342](https://github.com/fluttergems/awesome-open-source-flutter-apps/assets/149036369/4e93da2e-e54a-4127-af98-8d9eec419e66)
I mean Like this please review

**Comment by ashitaprasad** [comment]
This project does not require a table of contents, hence it was closed.
