### ISSUE TITLE
 Adding a open-source Finance app build with Flutter

### ISSUE THREAD

**Issue by Arpcoder** [fluttergems/awesome-open-source-flutter-apps#29]

**Comment by varshithar12** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue.

**Comment by Arpcoder** [comment]
> I agree to follow this project's Code of Conduct I'm a GSSOC'24 contributor I want to work on this issue.

Hello, I have opened it for myself. But you can open your own issue using New issue button
