### ISSUE TITLE
Add LUDO flutter app

### ISSUE THREAD

**Issue by arunimaChintu** [fluttergems/awesome-open-source-flutter-apps#290]
This adds LUDO flutter app

**Comment by ashitaprasad** [comment]
Add the github repo link here.

**Comment by arunimaChintu** [comment]
https://github.com/topics/ludo-game @ashitaprasad Please consider it... is it okay!

**Comment by arunimaChintu** [comment]
<img width="950" alt="Screenshot 2024-06-30 at 10 39 22 PM" src="https://github.com/fluttergems/awesome-open-source-flutter-apps/assets/99474881/b2bb8b92-c0f6-417b-8cfc-8340c269b6db">

**Comment by ashitaprasad** [comment]
This is not the github repo link.
Provide the valid github project link.

**Comment by arunimaChintu** [comment]
https://github.com/nizwar/ludo_flutter This? @ashitaprasad
