### ISSUE TITLE
Add new flutters app

### ISSUE THREAD

**Issue by root-0101** [fluttergems/awesome-open-source-flutter-apps#347]
- [flutter-chat-app](https://github.com/rohan20/flutter-chat-app) : A chat app made in flutter
- [inKino](https://github.com/roughike/inKino) : A movie app
- [Flare-Flutter](https://github.com/2d-inc/Flare-Flutter) : A game created with Flutter, designed to help developers learn Flutter 
- [Taskist](https://github.com/huextrat/Taskist) : Flutter Todo app

**Comment by ashitaprasad** [comment]
The listed projects are not active.
