### ISSUE TITLE
Add sMedical app

### ISSUE THREAD

**Issue by Asymtode712** [fluttergems/awesome-open-source-flutter-apps#396]
**sMedical**

(https://github.com/sagor1414/sMedical)

this is a complete doctor appointment app where user can appoint a doctor

**Category: Medical**

**Comment by Asymtode712** [comment]
@ashitaprasad please assign me this issue

**Comment by Asymtode712** [comment]
@ashitaprasad Can I please know the reason behind not getting 'level1' label??

**Comment by ashitaprasad** [comment]
@Asymtode712 Your name was specifically highlighted by the gssoc team which is why I cannot allocate level1 label.
