### ISSUE TITLE
Habit Tracker App in Flutter

### ISSUE THREAD

**Issue by vamzx** [fluttergems/awesome-open-source-flutter-apps#441]
An app that allows users to add, delete and edit habits and track them through their monthly heatmap. I will also be adding an offline database (Hive) to make it beginner friendly. 

(I am a GSSoC '24 Contributor and can work on this quickly)

**Comment by ashitaprasad** [comment]
Add the github link of the project here.

**Comment by vamzx** [comment]
@ashitaprasad [https://github.com/vamzx/Habit-Tracker](url)
Please let me know if you need any other changes added, I will work on them immediately

**Comment by ashitaprasad** [comment]
Similar projects are already present in the list.
