### ISSUE TITLE
to add open source flutter apps

### ISSUE THREAD

**Issue by Unnimaya6122004** [fluttergems/awesome-open-source-flutter-apps#46]
### You

(https://github.com/MDSADABWASIM/You)

This is a simple app that makes it easy to access your personal data. You can download your data that Google, Facebook, Instagram, Twitter collects.

**Comment by Unnimaya6122004** [comment]
can u pls assign me

**Comment by nachiketapte1404** [comment]
please assign this issue to me.

**Comment by ashitaprasad** [comment]
@nachiketapte1404 You can raise a new issue with the link of the project you want to add.
