### ISSUE TITLE
Add `E-commerse payment` application

### ISSUE THREAD

**Issue by sivaprasath2004** [fluttergems/awesome-open-source-flutter-apps#582]
- If i want to add the `E-Commerse` application future features are like `payment & cart` option.

### Project 

[Click here visit the project](https://shopping-application-iota.vercel.app/)

![Screenshot from 2024-07-24 10-36-27](https://github.com/user-attachments/assets/d28d1db8-762d-41dd-ac1c-51a1c5cc7474)

![Screenshot from 2024-07-24 10-37-41](https://github.com/user-attachments/assets/6ff5eb29-33d1-48ec-8802-ff7d43f87a96)

![Screenshot from 2024-07-24 10-38-50](https://github.com/user-attachments/assets/cd91755c-bed1-487f-a9bf-2ccc58ccbba9)

![Screenshot from 2024-07-24 10-39-39](https://github.com/user-attachments/assets/ab7e90b5-c83b-4fc6-bd40-bbed8082a3b6)

- please assign me.

**Comment by ashitaprasad** [comment]
Add the github link to the repo here.

**Comment by sivaprasath2004** [comment]
Hello @ashitaprasad ,

[repo link](https://github.com/sivaprasath2004/shopping-application)

**Comment by sivaprasath2004** [comment]
@ashitaprasad please assign me..
