### ISSUE TITLE
Want to add a flutter expenses App

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [fluttergems/awesome-open-source-flutter-apps#584]
I want to add a flutter expenses app 

https://github.com/a-l-l-a-n/Flutter_Personal_Expenses_App

**Comment by Ayushmaanagarwal1211** [comment]
@ashitaprasad  Can you please tell mw why it is inactive so that i will take care of it and will not issue for inactive projects

**Comment by ashitaprasad** [comment]
Please make sure that the project has been updated atleast once in the last year.
