### ISSUE TITLE
Add Object Detection App

### ISSUE THREAD

**Issue by Vaibhav-kesarwani** [fluttergems/awesome-open-source-flutter-apps#596]
which encourage users to embrace their knowledge in the field of computer vision and comprehend the primary purpose of object detection

**Comment by Vaibhav-kesarwani** [comment]
@ashitaprasad Please assign this issue to me

**Comment by ashitaprasad** [comment]
Add the github repo link

**Comment by Vaibhav-kesarwani** [comment]
sorry for late reply, link -> https://github.com/Vaibhav-kesarwani/flutter_realtime_object_detection
please assign this issue to me @ashitaprasad

**Comment by ashitaprasad** [comment]
Ethical violation - The project is copied from https://github.com/hiennguyen92/flutter_realtime_object_detection. You are being banned from making any more contributions to the project.
