### ISSUE TITLE
Add Mobile Payment App

### ISSUE THREAD

**Issue by Vaibhav-kesarwani** [fluttergems/awesome-open-source-flutter-apps#602]
This useful tool allows users to manage their finances while on the go. It was developed with Flutter.

**Comment by Vaibhav-kesarwani** [comment]
@ashitaprasad Please assign this issue to me

**Comment by ashitaprasad** [comment]
Add the github repo link.

**Comment by Vaibhav-kesarwani** [comment]
sorry for late reply, link ->  https://github.com/Vaibhav-kesarwani/mobile-payment-app
please assign this issue to me @ashitaprasad

**Comment by ashitaprasad** [comment]
Similar projects already present.
