### ISSUE TITLE
Add Barrett Flutter Simulation

### ISSUE THREAD

**Issue by Vaibhav-kesarwani** [fluttergems/awesome-open-source-flutter-apps#610]
This Flutter project simulates the operation of the Barrett 2090 and XV 3088 communication systems. It provides a user-friendly interface to experience the functionalities of these systems in a virtual environment. The simulation includes key features and controls to mimic real-world scenarios and interactions.

https://github.com/Vaibhav-kesarwani/barrett-2090-xv-3088-flutter-simulation

**Comment by Vaibhav-kesarwani** [comment]
@ashitaprasad Please assign me this issu

**Comment by ashitaprasad** [comment]
Project copied from - https://github.com/hadiuzzaman524/Barrett-2090-XV-3088-Flutter-Simulation
