### ISSUE TITLE
Text Generator App Using GPT-4.0

### ISSUE THREAD

**Issue by AmruthaPariprolu** [fluttergems/awesome-open-source-flutter-apps#633]
A multi-platform text generator app using GPT-4.0 and Flutter, providing various text generation features.

**Comment by ashitaprasad** [comment]
Add the github repo link.

**Comment by AmruthaPariprolu** [comment]
https://github.com/saba99/Text-Generator-App-Using-GPT-4.0

**Comment by AmruthaPariprolu** [comment]
@ashitaprasad 
i have added the link 
kindly assign me with this issue

**Comment by ashitaprasad** [comment]
Copied project.
