### ISSUE TITLE
AI Chatbot & Translator

### ISSUE THREAD

**Issue by AmruthaPariprolu** [fluttergems/awesome-open-source-flutter-apps#635]
A Flutter app developed for a hackathon, offering chatbot and translation functionalities using AI and LLMs.

**Comment by ashitaprasad** [comment]
Add the github repo link.

**Comment by AmruthaPariprolu** [comment]
Hackathon-AnadoluSigorta

**Comment by AmruthaPariprolu** [comment]
https://github.com/aydozy/Hackathon-AnadoluSigorta

**Comment by AmruthaPariprolu** [comment]
@ashitaprasad 
i have added the link 
kindly assign me with this issue

**Comment by ashitaprasad** [comment]
Low quality project.
