### ISSUE TITLE
Comind

### ISSUE THREAD

**Issue by AmruthaPariprolu** [fluttergems/awesome-open-source-flutter-apps#637]
A project focusing on social networking features with generative AI integrations.

**Comment by ashitaprasad** [comment]
Add the github repo link.

**Comment by AmruthaPariprolu** [comment]
https://github.com/mind-co/comind

**Comment by AmruthaPariprolu** [comment]
@ashitaprasad 
i have added the link 
kindly assign me with this issue

**Comment by ashitaprasad** [comment]
The app does not qualify the criteria for addition
