### ISSUE TITLE
Gemini CLI

### ISSUE THREAD

**Issue by AmruthaPariprolu** [fluttergems/awesome-open-source-flutter-apps#638]
A command-line tool that provides generative AI capabilities using Google's Gemini LLM.

**Comment by ashitaprasad** [comment]
Add the github repo link

**Comment by AmruthaPariprolu** [comment]
https://github.com/myConsciousness/gemini_cli

**Comment by AmruthaPariprolu** [comment]
@ashitaprasad 
i have added the link 
kindly assign me with this issue
