### ISSUE TITLE
Harmony Forge

### ISSUE THREAD

**Issue by AmruthaPariprolu** [fluttergems/awesome-open-source-flutter-apps#639]
A music generation platform merging Flask and Flutter, allowing users to create music through machine learning models.

**Comment by ashitaprasad** [comment]
Add the github repo link.

**Comment by AmruthaPariprolu** [comment]
https://github.com/jztchl/Harmony-Forge

**Comment by AmruthaPariprolu** [comment]
@ashitaprasad 
i have added the link 
kindly assign me with this issue
