### ISSUE TITLE
Add "Word-Matching-Game"

### ISSUE THREAD

**Issue by arunimaChintu** [fluttergems/awesome-open-source-flutter-apps#648]
https://github.com/khaled-0/Word-Matching-Game : Practice words with friends. Unleash your dictionary skills 🤓

**Comment by arunimaChintu** [comment]
@ashitaprasad please assign me this issue

**Comment by arunimaChintu** [comment]
@ashitaprasad Please assign me this issue

**Comment by ashitaprasad** [comment]
Similar projects are already present.
