### ISSUE TITLE
Add flutterFX to the list

### ISSUE THREAD

**Issue by amalChandran** [fluttergems/awesome-open-source-flutter-apps#665]
I am creating a collection of opensource animated widgets that any busy developer can quickly copy and paste into his app. each widget will have a set up manual instructing how to integrate into existing app and also the parameters that can be customised in the widget.  

Here is the project: https://github.com/flutterfx/flutterfx_widgets/

I think this will be such a value add to flutter developers. 

If you are okay with this, please suggest a category. The closest one I see is Templates. Please advice.

**Comment by ashitaprasad** [comment]
Currently you can add it to the Developer Tools category.
You can raise a PR by following our [CONTRIBUTING GUIDE](https://github.com/fluttergems/awesome-open-source-flutter-apps/blob/main/CONTRIBUTING.md)
Thanks!
