### ISSUE TITLE
Add Mindwrite to Lifestype apps

### ISSUE THREAD

**Issue by mohhamad-esmaili** [fluttergems/awesome-open-source-flutter-apps#666]
Name: MindWrite

Category: Lifestyle

Overview: MindWrite is a best practice app implementing Clean Architecture with the Bloc pattern and exploring technologies such as: equatable, image_picker, get_it, go_router, hive, and more. this is clone of google keepnote

GitHub Repo: [MindWrite](https://github.com/mohhamad-esmaili/mindwrite)

**Comment by ashitaprasad** [comment]
You can raise a PR by following our [CONTRIBUTING GUIDE](https://github.com/fluttergems/awesome-open-source-flutter-apps/blob/main/CONTRIBUTING.md)
Thanks!
