### ISSUE TITLE
Add ColorHap to Graphics & Design apps

### ISSUE THREAD

**Issue by TechAurelian** [fluttergems/awesome-open-source-flutter-apps#668]
Project Name: ColorHap

Category: Graphics & Design

Overview: A random color generator that shuffles millions of colors and lets you browse, preview, and select specific colors, save favorites, share color codes and swatches, and explore colors in detail.

GitHub Repository: [ColorHap](https://github.com/tecdrop/color_hap)

**Comment by ashitaprasad** [comment]
Thanks @TechAurelian. You can raise a PR by following our [CONTRIBUTING GUIDE](https://github.com/fluttergems/awesome-open-source-flutter-apps/blob/main/CONTRIBUTING.md)
