### ISSUE TITLE
Add Tomo desktop timer app to Productivity

### ISSUE THREAD

**Issue by k7d** [fluttergems/awesome-open-source-flutter-apps#675]
[Tomo](https://github.com/k7d/tomo) is a nice little desktop timer app for Pomodoro technique with realtime sync via Firebase.

<img width="480" alt="timer@2x" src="https://github.com/user-attachments/assets/a73f7418-7ffd-49e7-8adb-15186d6f8009">

**Comment by ashitaprasad** [comment]
Thanks @k7d . You can raise a PR by following our [CONTRIBUTING GUIDE](https://github.com/fluttergems/awesome-open-source-flutter-apps/blob/main/CONTRIBUTING.md)
