### ISSUE TITLE
Creation of Stateful widget, app bar , padding , scaffold widget and basic structure

### ISSUE THREAD

**Issue by anuragJoshi05** [fluttergems/awesome-open-source-flutter-apps#7]
I can provide you with a basic structure of a Flutter app that includes a stateful widget, app bar, padding, and scaffold widget, to make a start, please assign to me ......please

**Comment by pavants777** [comment]
Can you assign this project for me @fluttergems , I contributed more 10+ project of experiences, so i can resolve this project

**Comment by ashitaprasad** [comment]
Try understanding the project before raising an issue.
