### ISSUE TITLE
[Feature] : Bookmark the Article

### ISSUE THREAD

**Issue by sivaprasath2004** [fluttergems/awesome-open-source-flutter-apps#75]
- If the home page click to the `User Journey` first article `home-screen-launcher-icon-name/` , then `read more` the article.
- User can be save the article for the future purpose. 
- So when i can implement the new feature of the `bookmark the article` new feature.
- please assign me ..
- i will ready work in this project.

**Comment by ashitaprasad** [comment]
Please read the contribution guide to understand the project requirements.
