### ISSUE TITLE
Add Feature - Home Page

### ISSUE THREAD

**Issue by hariram62** [fluttergems/awesome-open-source-flutter-apps#8]
-> By creating a separate app, whose home page as the links for all the open-source flutter apps in GSSoC'24.
-> Listing them with proper UI

**Comment by hariram62** [comment]
I would like to contribute to this issue, can u pls assign me ?

**Comment by ashitaprasad** [comment]
Follow the contributing guide - https://github.com/fluttergems/awesome-open-source-flutter-apps/blob/main/CONTRIBUTING.md
We do not accept any issues/PRs outside the current scope.
