### ISSUE TITLE
Add Feature - Track the progress

### ISSUE THREAD

**Issue by hariram62** [fluttergems/awesome-open-source-flutter-apps#9]
-> Adding fields, so that user enters their ongoing contributions including issues raised, issues solved, no. of PR's for all flutter projects.
-> By this, the user can keep track of their progress.

**Comment by hariram62** [comment]
@ashitaprasad  I would like to contribute to this issue, can u pls assign me ?

**Comment by mayankgongal5** [comment]
I would like to contribute to this issue

**Comment by ashitaprasad** [comment]
Follow the contributing guide - https://github.com/fluttergems/awesome-open-source-flutter-apps/blob/main/CONTRIBUTING.md
We do not accept any issues/PRs outside the current scope.
