### ISSUE TITLE
Implementing Multilingual support

### ISSUE THREAD

**Issue by Anjankumarkamalapur** [fluttergems/awesome-open-source-flutter-apps#94]
I'll make sure users can view the website in their preferred language by adding a language selection option in the navbar. Users will be able to choose from available languages for a smoother browsing experience. As previously done in my last project, I used the Google translation widget to translate content on the website into multiple languages.
The below image is my last project where I made it available in different languages.
![image](https://github.com/fluttergems/awesome-open-source-flutter-apps/assets/139578011/a3d028b2-a93c-4677-8437-0c0b8579e7af)

**Comment by ashitaprasad** [comment]
Please read the contributing guide properly and understand what the project requires.
